#pragma config(Motor,  motorA,          motorLeft,     tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          motorRight,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
// tests/telemetry.c
//
// Originally part of the FTC Team 417 Software Starter Kit: www.ftc417.org/ssk
// Forked by the SAAS Robotics team: https://github.com/saasrobotics/telemetry
//
// Test code for the telemetry code.
// Why use this instead of the telemetry program in the Samples/ folder? Short answer:
// it's simpler, and frankly, I don't fully understand the Samples/ version yet. This file
// basically just comes along for the ride whne we commit library changes.

#define USE_DISPLAY_DIAGNOSTICS 0   // turn off the diagnostic display found in JoystickDriver.h

#include "..\telemetryFTC.h"
//#include "..\Music.h"

// note: this is x in the documentation file in doc/
const int dataToAdd = 11;
const int timesToTransfer = 10;

void InitializeMain()
{
    TelemetryInitialize();
    TelemetryUseBluetooth(true);
    //TelemetryUseUSB(false);
}

void DoTelemetry()
    {
    	for (int i = 0; i < timesToTransmit; i++)
    	{
    		for (int j = 0; j < dataToAdd; j++)
    		{
    			TelemetryAddInt32(nPgmTime);
    			Sleep(50);
    		}
    		TelemetrySend();
    		Sleep(10);
    	}
    	TelemetryAddString("done");
    }

task main()
    {
    // Telemetry init
    InitializeMain();

    DoTelemetry();

    // As the main task is exiting, so should all others; this will
    // allow the program to gracefully and fully terminate (without this
    // call, the readMsgFromPC() task, e.g., in joystickDriver.h will
    // keep the program alive).
    StopAllTasks();
}
