#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../../../Robotics2013-14/libraries/Motors.h"
#include "../../src/telemetryFTC.h"
#include "JoystickDriver.c"

/*

	IMPORTANT: DESIGNED FOR SAAS VARSITY'S JARVIS CHASSIS.

*/

// universal to all telemetry-enabled teliops
int Telemetry_MotorPowerData[6] = {0, 0, 0, 0, 0, 0};
const int Telemetry_SampleRate = 50;

// specific to this particular teliop
int rightpower, leftpower = 0;
int rightpowerGlobal, leftpowerGlobal = 0;

task updateTelemetry()
{
	while (true)
	{
		// right
		TelemetryAddInt32(Telemetry_MotorPowerData[3]);
		// left
		TelemetryAddInt32(Telemetry_MotorPowerData[4]);
		TelemetrySend();

		// sampling rate control
		Sleep(Telemetry_SampleRate);
	}
}

task main()
{
	// initialize telemetry data collection
	TelemetryInitialize();
	StartTask(updateTelemetry);
	while(true)
	{
		rightpower = joystick.joy1_y2/2;		//read joystick y values (both sticks)
		leftpower = joystick.joy1_y1/2;

		if(abs(rightpower) < 8) //deadband with threshold of 8
		{
			rightpower = 0;
		}

		if(abs(leftpower) < 8) //deadband with threshold of 8

		{
			leftpower = 0;
		}

		rightpowerGlobal = rightpower;
		leftpowerGlobal = -leftpower;

		// give telemetry some data to report back
		// FIXME, this is not the optimal way to do this
		Telemetry_MotorPowerData[3] = rightpowerGlobal;
		Telemetry_MotorPowerData[4] = leftpowerGlobal;

		I2C_SetMotorSpeed(S1, 2, 1, rightpowerGlobal);
		I2C_SetMotorSpeed(S1, 2, 2, leftpowerGlobal);
		Sleep(10);
	}
}
