#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../../../Robotics2013-14/libraries/Motors.h"
#include "../../src/telemetryFTC.h"

task updateTelemetry()
{
	while (true)
	{
		TelemetryAddInt32(I2C_GetEncoderPosition(S1, 1, 1));
		TelemetrySend();
		Sleep(100);
	}
}

task main()
{
	// initialize telemetry data collection
	TelemetryInitialize();
	StartTask(updateTelemetry);
	I2C_SetEncoderPosition(S1, 1, 1, 1000, 100);
	I2C_SetEncoderPosition(S1, 1, 1, -1000, 100);
	Sleep(10000000);
}
